<?php

namespace CMS\DashboardBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    public function findAllByInterval($start,$end)
    {
        return $this->getEntityManager()
                    ->createQueryBuilder('e')
                    ->select('e')
                    ->from('CMSDashboardBundle:Event','e')
                    ->where('e.date_debut BETWEEN :start and :end')
                    ->setParameters(array('start' => $start, 'end' => $end))
                    ->andWhere('e.date_fin BETWEEN :start and :end')
                    ->setParameters(array('start' => $start, 'end' => $end))
                    ->orderby('e.date_debut','ASC')
                    ->getQuery()
                    ->getResult();
    }
}
