<?php

namespace CMS\BlocBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlocBreadcrumbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocBreadcrumbRepository extends EntityRepository
{
}
