<?php

namespace CMS\BlocBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocMenuRepository extends EntityRepository
{

    public function findBloc($id)
    {
        return $this->getEntityManager()
                    ->createQueryBuilder('b')
                    ->Select('b')
                    ->from('CMSBlocBundle:BlocMenu','b')
                    ->join('b.menu','m')
                    ->join('m.menus', 'me')
                    ->where('b.id=:id')
                    ->setParameter('id', $id)
                    ->andWhere('me.published=:published')
                    ->setParameter('published',1)
                    ->getQuery()
                    ->getSingleResult();
    }

}
