<?php

namespace CMS\SitemapBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SitemapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitemapRepository extends EntityRepository
{
}
