<?php

namespace CMS\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function getAllUsersQuery() {
		return $this->_em
					->createQueryBuilder('u')
					->select('u')
					->from('CMSAdminBundle:User', 'u')
					->getQuery();
	}
}