parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: chrisSymfony
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 76007789b14f0abdb99499bf4a4fc4a4a18b842d
    database_path: null
