<?php

namespace CMS\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{

	public function getAllFieldsArray()
	{
		return $this->_em
					->createQueryBuilder()
					->select('f.name,f.title')
					->from('CMSContentBundle:CMField','f')
					->getQuery()
					->getArrayResult();
	}
}