<?php

namespace CMS\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaRepository extends EntityRepository
{

	 public function getMetaQuery()
    {
        return $this->_em
                    ->createQueryBuilder()
                    ->select('c')
                    ->from('CMSContentBundle:CMMeta', 'c')
                     ->orderby('c.created', 'desc')
                    ;
    }
}
