<?php

namespace CMS\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

	public function getAllTags()
	{
		return $this->_em
					->createQueryBuilder()
					->select('t')
					->from('CMSContentBundle:CMTag', 't')
					->orderby('t.title', 'asc')
					->getQuery()
					->getArrayResult();
	}

	public function getAllTagsTitleObject()
	{
		$tags = $this->_em
					->createQueryBuilder('t')
					->select('t')
					->from('CMSContentBundle:CMTag', 't')
					->orderby('t.title', 'asc')
					->getQuery()
					->getResult();

		$tags_result = array();		

		foreach ($tags as $tag) { 
			$tags_result[$tag->getTitle()] = $tag;
		}		
		return $tags_result;			
	}

	public function getAllTagsTitle()
	{
		$tags = $this->_em
					->createQueryBuilder('t.title')
					->select('t.title')
					->from('CMSContentBundle:CMTag', 't')
					->orderby('t.title', 'asc')
					->getQuery()
					->getArrayResult();

		$tags_result = array();		

		foreach ($tags as $tag) { 
			$tags_result[] = $tag['title'];
		}		
		return $tags_result;
	}
}
