<?php

namespace CMS\ContactBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

    public function getNbMessageNotRead()
    {
        return count($this->_em
                    ->createQueryBuilder()
                    ->select('m')
                       ->from('CMSContactBundle:Contact', 'm')
                       ->where('m.statut = :statut')
                     ->setParameter('statut', 0)
                    ->getQuery()
                       ->getResult());
    }
}
