<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Trsteel\\CkeditorBundle' => array($vendorDir . '/trsteel/ckeditor-bundle'),
    'Symfony\\Bundle\\SwiftmailerBundle' => array($vendorDir . '/symfony/swiftmailer-bundle'),
    'Symfony\\Bundle\\MonologBundle' => array($vendorDir . '/symfony/monolog-bundle'),
    'Symfony\\Bundle\\AsseticBundle' => array($vendorDir . '/symfony/assetic-bundle'),
    'Symfony' => array($vendorDir . '/symfony/symfony/src'),
    'SessionHandlerInterface' => array($vendorDir . '/symfony/symfony/src/Symfony/Component/HttpFoundation/Resources/stubs'),
    'Sensio\\Bundle\\GeneratorBundle' => array($vendorDir . '/sensio/generator-bundle'),
    'Sensio\\Bundle\\FrameworkExtraBundle' => array($vendorDir . '/sensio/framework-extra-bundle'),
    'Sensio\\Bundle\\DistributionBundle' => array($vendorDir . '/sensio/distribution-bundle'),
    'Ornicar\\GravatarBundle\\' => array($vendorDir . '/ornicar/gravatar-bundle'),
    'Mopa\\Bundle\\BootstrapBundle' => array($vendorDir . '/mopa/bootstrap-bundle'),
    'Mopa\\Bridge\\Composer' => array($vendorDir . '/mopa/composer-bridge/src'),
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'Liip\\ImagineBundle' => array($vendorDir . '/liip/imagine-bundle'),
    'Knp\\Component' => array($vendorDir . '/knplabs/knp-components/src'),
    'Knp\\Bundle\\PaginatorBundle' => array($vendorDir . '/knplabs/knp-paginator-bundle'),
    'JMS\\SecurityExtraBundle' => array($vendorDir . '/jms/security-extra-bundle'),
    'JMS\\DiExtraBundle' => array($vendorDir . '/jms/di-extra-bundle'),
    'JMS\\AopBundle' => array($vendorDir . '/jms/aop-bundle'),
    'Imagine' => array($vendorDir . '/imagine/Imagine/lib'),
    'Gedmo' => array($vendorDir . '/gedmo/doctrine-extensions/lib'),
    'Doctrine\\ORM' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DataFixtures' => array($vendorDir . '/doctrine/data-fixtures/lib'),
    'Doctrine\\DBAL' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common' => array($vendorDir . '/doctrine/common/lib'),
    'Doctrine\\Bundle\\DoctrineBundle' => array($vendorDir . '/doctrine/doctrine-bundle'),
    'CG\\' => array($vendorDir . '/jms/cg/src'),
    'Avalanche\\Bundle\\ImagineBundle' => array($vendorDir . '/avalanche123/imagine-bundle'),
    'Doctrine\\Bundle\\FixturesBundle' => array($vendorDir . '/doctrine/fixtures-bundle/'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
    '' => array($baseDir . '/src'),
);
